import './css/textcontent.css';
import imgText from './images/inicio-text-1.jpg';

const text = `
<h2>Reflexiones a propósito de habitar el espacio público como acto disruptivo frente a la planificación urbana, en los barrios patrimoniales de la ciudad de Medellín- Prado centro, Boston, y Los Ángeles.</h2>
<img src=${imgText}> 
<p>Este proyecto investigativo, surge durante mi permanencia en la ciudad de Medellín, a partir de la atención en algunas dinámicas socio - espaciales, que manifiestan la disonancia en que se revela la urbe y las cuales permiten construir nuevas significaciones, e interpretaciones de la realidad concreta.</p>
<p>La ciudad se presenta como un sistema complejo, en el cual confluyen un sinnúmero de categorías sociales, económicas y políticas; una multiplicidad de esferas urbanas y prácticas cotidianas contrarias, en permanente transformación.  Esta manifestación heteróclita de la sociedad oscila entre la contención y el acontecer de lo espontáneo que emerge de escenarios alternos, y sirve como punto de partida de una serie de consideraciones, en torno a la ocupación del espacio público, y las formas espaciales que se generan allí.</p>
<p>Teniendo como referencia algunas problemáticas sociales; como la notable presencia de personas en condición de calle &lt habitante de calle &gt,  el microtráfico, la prostitución, el comercio informal, entre otras prácticas irregulares, en relación con el lugar que ocupan, encuentro una notable correspondencia con el sector patrimonial de Medellín. El barrio Prado centro, Los Ángeles y parte del sector de Boston. Allí se presentan vínculos que evidencian los contrastes y desarticulan la imagen de la ciudad, cuestionando la igualdad de acceso al espacio público, el desplazamiento constante del patrimonio habitado, el arquitectónico y la pérdida de la memoria urbana.</p>
<p>El color deviene a modo de paleta de ciudad, como marcaje urbano, fachada y como elemento que se yuxtapone constantemente entre las dinámicas urbanas del patrimonio habitado y arquitectónico.</p>
<p>*</p>
<p>El espacio público y cada uno de los elementos urbanos que lo componen, se ha ido convirtiendo cada vez más, en un medio pertinente en el cual se exponen las problemáticas y las condiciones sociales de un lugar; allí, se revelan las inconsistencias que desde antes han existido, incontenibles en el devenir de nuestra sociedad.</p>
<p>A modo de apropiaciones del espacio, como marcajes, ocupaciones temporales del espacio público o a través de pintadas o grafitis callejeros, que alteran el paisaje urbano, desarticulando así, las políticas de linealidad y regulación frente a la ocupación de este; adquieren un poder esencial, los elementos urbanos, como vinculación especifica entre la necesidad de denunciar y a la vez transformar. </p>
<p>**</p>
<p>En medio de algunas estrategias de recuperación e intervención, de las fachadas de las antiguas casas del barrio Prado Centro en Medellín, que se han hecho a través de la administración municipal; como procesos de peatonalización, pintura de fachadas y recuperación del color; emergen grafitis callejeros, a partir de gestos espontáneos y veloces; estas expresiones visuales, se yuxtaponen sobre el paisaje arquitectónico, transformándolo y  apoderándose paulatinamente de él, como un medio transgresor y de denuncia, casi propiciando un recorrido espacial que agita visualmente  la aparente rectitud de la estética arquitectónica y el mobiliario urbano, que se intenta reservar y mantener hermético ante cualquier asomo de contrariedad.</p>
<p>Las pintadas o grafitis, visibilizan el estado de la sociedad inconforme, que se proyecta por fuera de lo apropiado y lo hegemónico, reconfigurando el espacio al paso de los días, de manera orgánica y en sintonía a los sentimientos de sus realizadores; de este mismo modo, empiezan a resistirse a los principios del urbanismo, personas que acogen y crean nuevas formas de urbanismo y estéticas urbanas, paralelas a las de la ciudad planificada. Contrarrestando así, la imposición institucional, a través de equipamientos no convencionales que se despliegan ocasionalmente en el espacio y doblegan las políticas de orden público, de manera disruptiva.</p>
<p>Pero estos modos de ocupación temporal del espacio público, que en algunos casos se pueden manifestar como un gesto libre, de simple irreverencia,  le hacen frente a profundas problemáticas sociales de desigualdad e inestabilidad, a una precariedad política y económica, que de algún modo se encuentra normalizada, y de la cual surgen soluciones por instinto de supervivencia.</p>
<blockquote>
&quotVivimos en una era en la que los ideales de los derechos humanos se han colocado en el centro de la escena tanto política como éticamente. Se ha gastado una gran cantidad de energía en promover su significado para la construcción de un mundo mejor, aunque la mayoría de los conceptos que circulan no desafían fundamentalmente las lógicas de mercado liberales y neoliberales o los modos dominantes de legalidad y de acción estatal. Vivimos, después de todo, en un mundo en el que los derechos a la propiedad privada y el beneficio aplastan todas las demás nociones de derechos.&quot

    -David Harvey, el derecho a la ciudad.
</blockquote>
<p>La presencia de estas personas y sus ocupaciones, se convierte en un marcaje social, que señala, provee de ciertas características y configura la relación del resto de los habitantes de la ciudad con el barrio. Son estas prácticas irregulares, las que acentúan de algún modo el patrimonio habitado de un lugar en el que las viviendas han quedado relegadas a instituciones, donde de puertas para adentro se tejen relaciones, pero que en sus calles, no existe necesariamente un vínculo comunitario.  Con todo esto se crean limitantes que hacen parte de la construcción social,  una sensación de inseguridad, que como lo señala Jane Jacobs acerca de los ojos en la calle, determinan la postura que se tiene con las calles del barrio y con estas mismas prácticas y personas, que de algún modo se les margina.</p>
<p>***</p>
<h3>En tiempos de pandemia.</h3>
<p>El contexto de la emergencia sanitaria por Covid 19, evidentemente condicionó la manera como nos relacionamos con el espacio público y con los demás habitantes de la ciudad.</p>
<p>Este ha sido un detonante que ha permitido mayor visibilidad a  las diversas problemáticas sociales que se intensificaron en medio de la situación, en temas económicos y espaciales.</p>
<p>Es de allí, como el andén del espacio público en el barrio, que permanece dispuesto, pasa de contemplar y de ser el escenario desde donde se atiborra y sucede la cotidianidad social inmediata, a ser contemplado, queda desprovisto de todo tipo de comercio. Los condicionamientos de este espacio, se hacen más notables, se acentúa la negación de un espacio público para el vendedor ambulante, donde sobresale el rígido control que siempre ha existido frente a este elemento del urbanismo que se supone para ser vivenciado.</p> 
<p>A fuerza, se enfatiza el ejercicio de rebeldía, que hace cotidianamente el habitante - vendedor ambulante, que en su práctica genera lazos sociales y desde donde se tejen confrontaciones y convivencias espaciales, que posibilitan la experiencia social del vecindario.</p>
<p>De modo contrario, este andén del espacio público para los habitantes de la calle, las personas que deben vivir allí,  se ha vuelto un espacio de refugio ocasional, su acto de rebeldía frente a la negación del habitar la calle en tiempos de pandemia, es sencillamente una presentación de la marginalidad. La ocupación efímera y cambiante que hace el habitante de este sitio, transgrede la expectativa social.</p>
<p>En medio del eclecticismo arquitectónico de barrio, se presenta el suelo como refugio, sombra y descanso, acoge una presencia tan solo vista, siquiera capaz de ser percibida, como un sobresalto a la vista, que particularmente rompe la continuidad y produce precaución en el transeúnte.</p>
<p>****</p>
<p>En épocas de conectividad virtual, el servidor web Street view encapsula, y eterniza por tiempos medianamente duraderos, acontecimientos del espacio público habitado que ideológicamente han intentado ser disimulados en la realidad concreta. Como una galería de la realidad tal cual es, sin desaprobación alguna, fragmentos de vivencias espaciales y acontecimientos espontáneos de la sociedad, quedan congelados y se vuelven universales.</p>
<p>Desde lo medianamente lejano, surgen formas, que tienden a volverse indescifrables, como pequeñas insinuaciones de color, casi con un aspecto de código de ciudad, multiforme, y empiezan a adquirir un aspecto de señalamiento sobre el paisaje urbano, que sobresale. Pasajes de seres humanos en situaciones que enaltecen la subjetividad que los compone, o formas semiescondidas detrás de árboles, escalones, bolsas, entre otros; que sugieren la presencia de un cuerpo humano apropiado a su antojo del espacio público. Algunas de estas personas, traen consigo elementos, que de modo ingenioso se convierten en construcciones habitables temporales y transportables, que sugieren quizás una pregunta por lo escultórico, quizás como otra posibilidad entre la arquitectura y el paisaje, sobre las que alguna vez intentó cartografiar Rosalind Krauss.</p>
<p>Emplazamientos efímeros a partir de elementos reciclados, transformados, relocalizados, recontextualizados, que genera una heterotopìa espacial, y se yuxtapone al paisaje arquitectónico regular.</p>
<h3>Aproximaciones al color.</h3>
<p>La experiencia que existe a través del color es producto directo de la presencialidad. Necesariamente la manera como percibimos las pulsiones del color, están profundamente ligadas a atributos culturales y a la propia manera de relacionarnos con el color en nuestro entorno cultural. Incluso aspectos de la geografía de un lugar, relacionado a condiciones específicas del clima, atmosféricas, entre otros; condicionan el comportamiento de un territorio, aportando significativamente a los valores estéticos de cada cultura.</p>
<p>Aun así, la experiencia que tenemos con el color es necesariamente particular. Olafur Eliasson menciona, “El color tiene un enorme potencial psicológico y asociativo: aun cuando se ha cultivado hasta el extremo, la experiencia de los colores es así mismo extremadamente individual.” (O, Eliasson, 2012)</p>
<p>Partir de una imagen, recomponer, reconfigurar, extraer de ella su mínimo punto de homogeneidad, vacilar a partir de la saturación, el matiz, el aspecto cromático, su intensidad y encontrar la posición enriquecida en la cual la mirada acude a la inquietud, a la ambigüedad de lo eventual, ya no en movimiento, sino como un hecho capturado en el instante que se prolonga en el tiempo. Un punto de la imagen que se correlaciona directamente con otros mínimos elementos, y en esa interrelación, surge una exploración visual, que golpea el ojo al contacto.</p>
<p>Estamos aprehendidos a lo móvil, al evento furtivo y pasajero, pestañeamos al tiempo en que se reconfigura el espacio con sus eventualidades, y la imagen pocas veces se adhiere, pocas veces trasciende y se expande en el tiempo. Recorrer la ciudad, optar por una posición receptiva en sus calles, en ocasiones produce desgaste, debido a la sonoridad visual y la facilidad en la que se pasa de una imagen a otra. Los eventos dejan de ser eventos, para convertirse en presunciones cotidianas, banales, que pierden la calidad para ser exploradas, más allá de la forma.</p>
<p>A partir del mínimo elemento de color que compone una imagen digital enmarcada de la realidad, se reconstruye su significado, el desvanecimiento de la figuración señala el color por sí mismo.</p>
<p>El cuerpo urbano nos posiciona constantemente como espectadores de pequeñas realidades fragmentadas de la ciudad, al tiempo en que estas orgánicamente se van posicionando en la superficie del escenario social; por otro lado se les impide fluir, en medio de la vigilancia que bajo nociones del bien común y un marketing urbanístico en el cual prima la estética y al armonía visual, se esconden marginalidades, que se disimulan constantemente dentro del aparataje político, desvaneciendo estas realidades específicas. La presencia de estos hechos cotidianos, en el acontecer diario, empiezan a perder relevancia para el usuario de la ciudad.</p>
<p>La codificación de la imagen permite señalar estas prácticas, potenciando el valor de la inaceptación, negación y camuflaje.  El carácter silencioso que han adquirido estas prácticas se trastoca con la necesidad de ocultación de la imagen que incomoda, con el interés de deslocalizar y resituar en el plano social, la posición de estas prácticas con el espacio que ocupan.</p>
<p>El aspecto comunicativo del color atribuye otra mirada de la realidad, al yuxtaponerse a la estandarización cromática del entorno urbano. La instrumentación y los elementos requeridos por estas personas para sobrellevar los aspectos más básicos de la subsistencia en el entorno urbano empiezan a generar contrastes visuales. En la proximidad de los espacios temporales que se van generando, los cuales les permiten acudir y gestionar sus necesidades más cercanas.</p>
`;

export function textContent() {
    const textContainer = document.createElement("article");
    textContainer.id = "text-container";
    textContainer.innerHTML = text;

    return textContainer
}